# ============================================================
# UAV Camera-LiDAR Dataset Configuration
# ============================================================

simulation:
  fps: 10
  num_frames: 300
  random_seed: 42

traffic:
  enabled: true
  num_vehicles: 40
  tm_port: 8000


# ============================================================
# UAV BODY
#
# 这里描述的是“无人机机体”的位置，不是 Camera 的姿态。
#
# CARLA:
#   x = forward
#   y = right
#   z = up
#
# pitch / roll 第一阶段保持 0。
# yaw 表示无人机机头朝向。
# ============================================================

uav:

  initial_pose:
    x: -60.5942
    y: 138.0428
    z: 50.0000

    pitch: 0.0
    yaw: -2.2371
    roll: 0.0


  route_file: "routes/route_01.yaml"



# ============================================================
# SENSOR RIG
# ============================================================

sensors:

  # ----------------------------------------------------------
  # LiDAR
  #
  # LiDAR 定义为 UAV 原点。
  #
  # 注意：
  # CARLA 的旋转 LiDAR 不需要 pitch=-90。
  #
  # Actor 保持水平：
  # pitch = 0
  #
  # 通过 upper_fov / lower_fov
  # 让所有激光朝向地面。
  # ----------------------------------------------------------

  lidar:

    position:
      x: 0.0
      y: 0.0
      z: 0.0

    rotation:
      pitch: 0.0
      yaw: 0.0
      roll: 0.0

    channels: 64

    range: 120.0

    points_per_second: 600000

    rotation_frequency: 10.0

    horizontal_fov: 360.0

    # 对地扫描
    #
    # -89° ≈ 几乎垂直向下
    # -45° = 外围激光
    #
    # 因此形成一个向下的圆锥形扫描区域。

    upper_fov: -45.0
    lower_fov: -89.0


  # ----------------------------------------------------------
  # RGB CAMERA
  # ----------------------------------------------------------

  camera:

    # Camera 位于 LiDAR 右侧 10 cm
    #
    # lidar  : y = 0.00
    # camera : y = 0.10
    #
    # 两者距离 = 0.10 m

    position:
      x: 0.0
      y: 0.10
      z: 0.0

    # ==============================
    # 当前测试姿态：
    # 正下视 Camera
    # ==============================

#    rotation:
#      pitch: -90.0
#      yaw: 0.0
#      roll: 0.0


    # ==============================
    # 备用姿态：
    #
    # Camera 朝 UAV 前方，
    # 并与地平线向下成 45°。
    #
    # 使用时：
    # 把上面的 rotation 注释，
    # 把下面这三行取消注释即可。
    # ==============================

    rotation:
       pitch: -45.0
       yaw: 0.0
       roll: 0.0


    width: 1280
    height: 720
    fov: 90.0


output:

  root: dataset

  save_rgb: true
  save_lidar: true
  save_pose: true
