########################## 静态测试路线：UAV 不移动，用于检查相机、LiDAR 和标定 ################################

route:

  name: "static_test"

  mode: waypoints

  speed_mps: 0.0

  loop: false

  waypoints:
    - x: -60.594
      y: 138.043
      z: 55.0
    - x: -50.764
      y: 21.184
      z: 34.489
    - x: 54.105
      y: -59.182
      z: 56.784
    - x: 102.64
      y: 28.542
      z: 62.019
