route:

  name: "route_01"


  # ==========================================================
  # MODE
  #
  # static
  # waypoints
  # ==========================================================

  mode: waypoints


  # ==========================================================
  # HEADING
  #
  # UAV 机头始终朝向当前路线段的下一个 waypoint。
  # ==========================================================

  heading_mode: follow_route


  # ==========================================================
  # WAYPOINTS
  #
  # waypoint 模式下：
  #
  # waypoint[0]
  # =
  # UAV 数据集录制起点
  #
  # waypoint[-1]
  # =
  # UAV 数据集录制终点
  # ==========================================================

  waypoints:

    - x: -83.14
      y: 130.873
      z: 42.107

    - x: -47.659
      y: 123.699
      z: 42.342

    - x: -46.944
      y: 110.872
      z: 42.342

    - x: -46.609
      y: -55.612
      z: 42.342

    - x: -0.565
      y: -61.928
      z: 42.342

    - x: 61.089
      y: -59.656
      z: 42.342

    - x: 80.887
      y: -54.266
      z: 42.342

    - x: 97.235
      y: -41.126
      z: 42.342

    - x: 102.123
      y: -11.84
      z: 42.342

    - x: 99.831
      y: 94.281
      z: 42.342

    - x: 93.231
      y: 112.921
      z: 42.342

    - x: 79.726
      y: 127.553
      z: 42.342

    - x: 61.569
      y: 138.071
      z: 42.342

    - x: -47.633
      y: 138.704
      z: 42.342
